### PR TITLE
#34 Docker Setup

### LINKED ISSUE #34: Task: Docker Setup

### PR DESCRIPTION
**Pull request by emilie-martin**
Set up Docker in the project to be able to build images locally. Resolves #34

### CODE REVIEW

**Comment by huangs08** [comment]
Could you change from main to development? We decided to push onto main only at the end of every sprint, and everyone should only pull from the development branch. Thanks!

**Review by huangs08 — APPROVED** [review]
great job!

**Review by Manraj45 — COMMENTED** [review]
It seems like you only dockerized the app (port 3000) and forgot about the port 4000 for the authentication server

**Review by Manraj45 — CHANGES_REQUESTED** [review]
It seems like you only dockerized the app (port 3000) and forgot about the port 4000 for the authentication server

**Comment by emilie-martin** [comment]
As decided during our team meeting, we will leave this merge request on hold until MySQL has been dockerized.

**Pull request closed without merging**
